### ISSUE TITLE
Change from homegrown to mpRestClient for Stock-Quote has altered behavior.

### ISSUE THREAD

**Issue by BarDweller** [IBMStockTrader/portfolio#11]
Originally ALL headers were cloned from the source request to the outbound request to StockQuote, (via `copyFromRequest` now only the JWT header is being passed on (as an arg to mpRestClient). 

Please confirm/document the expected behavior, so other implementations know what is expected.

Cloning all headers might seem excessive, but it would allow for trace span headers to propagate, so wouldn't be entirely unexpected for this kind of onward propagation.

**Comment by jwalcorn** [comment]
Yes, I was told it is actually a potential security exposure to blindly copy all headers/cookies, so I changed to only copy what was needed by the downstream microservice (generally, the Authorization header).

I've been told that "magic" happens when you enable the mpOpenTracing feature, which somehow intercepts outbound http requests and adds the trace span headers.  I've not confirmed this myself.  If you confirm that there is some problem with these open tracing headers, please open another issue.  Thanks.
