### ISSUE TITLE
Portfolio does not call Watson service from IKS

### ISSUE THREAD

**Issue by greghint** [IBMStockTrader/portfolio#8]
Stock Trader portfolio service works great in ICP.

However, when we port it to IKS, the Watson service does not get called.

```[INFO    ] Calling Watson Tone Analyzer
[INFO    ] Error from Watson
[WARNING ] javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
[INFO    ] javax.ws.rs.WebApplicationException: HTTP 400 Bad Request```

```{“message”: “Error communicating with the Watson Tone Analyzer”, “free”: 0, “sentiment”: “Unknown”}```

Here's what we know:
- Works fine in ICP
- Tried multiple Tone Analyzer services but no luck
- We confirmed the failure on other IKS instances, so it's not limited to our instance.

**Comment by jwalcorn** [comment]
I'm pretty sure this was the problem caused by my move to mpRestClient and JSON-B to call Watson Tone Analyzer, where I initially had the verb as GET instead of POST (due to a copy/paste error from an mpRestClient that was a GET).  If this problem is in fact still present, please re-open - but I think I fixed it last week.
